<script setup>
import {ref,reactive,computed,onMounted,onBeforeUnmount,watch,nextTick} from 'vue';
import {toPng} from 'html-to-image';
import RecognitionImage from './RecognitionImage.vue';
import CameraDialog from './CameraDialog.vue';
import HardwareControls from './HardwareControls.vue';
import TomatoGrowth from './TomatoGrowth.vue';
import MqttStatusPanel from './MqttStatusPanel.vue';
import MqttConfigDrawer from './MqttConfigDrawer.vue';
import KnowledgeWorkspace from './KnowledgeWorkspace.vue';import Trend from './Trend.vue';import {api,download,setSessionRecovery} from './api';
const classroomHero='/assets/tomato-growth/fruiting.png';
const campusSidebar='/assets/tomato-growth/seedling.png';
const nav=[['overview','总览','home-5-fill','课堂总览'],['courses','课堂任务','clipboard-line','课程与实训中心'],['iot','设备物联','node-tree','智能温室物联网'],['growth','劳动教育','leaf-fill','番茄生长周期科普'],['maturity','科技探究','flask-line','成熟度管理中心'],['devices','班级成果','bar-chart-box-line','多设备与班级成果'],['knowledge','课程资源','book-open-fill','知识库与智能问答'],['logs','AI 助教','robot-2-line','AI 日志与助教记录'],['archives','教学档案','folder-3-fill','生长档案']];
const metrics=[['air_temp','空气温度','°C','temp-hot-line'],['humidity','空气湿度','%','drop-line'],['light','光照','lx','sun-line'],['ec','EC','mS/cm','pulse-line'],['ph','pH','','flask-line'],['level','液位','%','water-percent-line'],['water_temp','水温','°C','temp-cold-line']];
const actuators=[['pump','水泵','water-flash-line','循环营养液，保持供水'],['light','补光灯','lightbulb-line','调节光照时长'],['fan','通风','windy-line','调节空气流通'],['mist','水雾','drizzle-line','调节空气湿度']];
function currentRoute(){const id=location.hash.slice(1)||'overview';if(id==='settings'){history.replaceState(null,'','#iot');return 'iot'}return id}
const route=ref(currentRoute()),subtab=ref('问答'),user=ref(null),deviceId=ref(''),devices=ref([]),answer=ref(null),question=ref('番茄叶片发黄怎么办？'),selection=ref('暂无关系'),sources=ref([]),rows=ref([]),tasks=ref([]),submissions=ref([]),alerts=ref([]),commands=ref([]),trend=ref([]),period=ref('day'),metric=ref('ph'),filter=ref(''),batchFilter=ref(''),loading=ref(false),message=ref(''),error=ref(''),mqtt=ref({connected:false}),busy=ref(false),profile=ref(false),loginOpen=ref(false),loginRole=ref('teacher'),loginPassword=ref(''),demo=ref(true),uploadEl=ref(),cameraEl=ref(),photoPurpose=ref('archive'),recognition=ref(null),compare=ref([]),recognitionDemo=ref(false),graphRef=ref(),trendRef=ref(),workspace=ref(),cameraOpen=ref(false),cameraMode=ref('local'),remoteCameraUrl=ref(''),savedCameraUrl=ref(''),pendingPhoto=ref(null),mqttDrawerOpen=ref(false);let timer,poll;
const dialog=reactive({open:false,title:'',fields:[],data:{},action:null,description:''});
const queryBusy=ref(false),modelStatus=ref({ready:false,state:'loading'}),confidencePercent=ref(65);
const modelNotice=computed(()=>modelStatus.value.ready?'番茄成熟度模型已就绪 · 可识别未成熟、半成熟、成熟':modelStatus.value.error||(modelStatus.value.state==='not_configured'?'识别模型尚未配置，请联系管理员。':'识别模型暂不可用，请稍后重试。'));
const summary=ref({}),archiveCompare=ref([]),achievements=ref({points:0,badges:[]});
const current=computed(()=>devices.value.find(d=>d.id===deviceId.value)||{}),values=computed(()=>current.value.latest?.values||{}),currentTitle=computed(()=>nav.find(n=>n[0]===route.value)?.[3]||'预警中心'),canTeach=computed(()=>['teacher','admin'].includes(user.value?.role)),canEdit=computed(()=>!!user.value&&user.value.role!=='parent'),allFiltered=computed(()=>rows.value.filter(x=>(!filter.value||JSON.stringify(x).includes(filter.value))&&(!batchFilter.value||x.batch===batchFilter.value))),dateLabel=computed(()=>new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})),weekdayLabel=computed(()=>['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][new Date().getDay()]),growthDays=computed(()=>current.value.planted?Math.max(0,Math.floor((Date.now()-new Date(current.value.planted))/86400000)):'—'),onlineDevices=computed(()=>devices.value.filter(device=>device.online).length),completedTasks=computed(()=>new Set(submissions.value.filter(item=>['submitted','evaluated'].includes(item.status)).map(item=>item.task_id)).size);
const selectedRecognition=computed(()=>recognition.value||allFiltered.value[0]);
function visibleDetections(record){return (record?.detections||[]).filter(d=>d.confidence>=confidencePercent.value/100)}
function filteredStats(record){
 const detections=visibleDetections(record),distribution={'未成熟':0,'半成熟':0,'成熟':0};
 for(const d of detections)distribution[d.label]=(distribution[d.label]||0)+1;
 return {fruit_count:detections.length,maturity_distribution:distribution,average_confidence:detections.length?detections.reduce((total,d)=>total+d.confidence,0)/detections.length:null};
}
const recognitionStats=computed(()=>selectedRecognition.value?filteredStats(selectedRecognition.value):null);
function metricUnit(m,record){return record?.units?.[m[0]]??m[2]}
function notify(text){message.value=text;clearTimeout(timer);timer=setTimeout(()=>message.value='',4000)}
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{return await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
function go(id){route.value=id;location.hash=id;subtab.value='问答';filter.value='';batchFilter.value='';profile.value=false}
function hash(){route.value=currentRoute()}
setSessionRecovery(async()=>{
 const role=user.value?.role||loginRole.value;
 try{const health=await api('/health');demo.value=health.demo;if(demo.value){user.value=await api('/session',{role});return true}}catch{}
 loginRole.value=role;user.value=null;loginOpen.value=true;error.value='登录已失效，请登录后继续；已拍照片会保留。';return false;
});
async function signIn(role='teacher',password=''){user.value=await api('/session',{role,password});demo.value=user.value.demo;loginOpen.value=false;error.value='';await refresh();await loadCameraConfig();if(pendingPhoto.value)await savePendingPhoto();await loadRoute();}

async function refresh(){const results=await Promise.all([api('/devices'),api('/mqtt'),api('/alerts'),api('/commands')]);devices.value=results[0];if(!devices.value.some(d=>d.id===deviceId.value))deviceId.value=devices.value[0]?.id||'';mqtt.value=results[1];alerts.value=results[2];commands.value=results[3]}
async function loadRoute(){if(!user.value)return;loading.value=true;try{
 if(['iot','overview'].includes(route.value)&&deviceId.value){const r=await api(`/telemetry/${deviceId.value}?period=${period.value}`);trend.value=r.points;rows.value=await api('/recognitions?device='+deviceId.value);summary.value=await api('/summary/'+deviceId.value)}
 if(route.value==='overview')[tasks.value,submissions.value]=await Promise.all([api('/tasks'),api('/submissions')]);
 if(route.value==='archives')rows.value=await api('/records?device='+deviceId.value);
 if(route.value==='logs')rows.value=await api('/logs');
 if(route.value==='maturity'){const [records,health]=await Promise.all([api('/recognitions?device='+deviceId.value),api('/health')]);rows.value=records;modelStatus.value=health.model||{ready:false,state:'not_configured'}}
 if(route.value==='courses'){[tasks.value,submissions.value]=await Promise.all([api('/tasks'),api('/submissions')])}
 if(route.value==='profile'){rows.value=await api('/favorites');achievements.value=await api('/achievements/me')}
 }catch(e){error.value=e.message}finally{loading.value=false}}
async function snapshot(){const r=await api(`/devices/${deviceId.value}/snapshot`,{});notify('设备上报值已保存到生长档案，空读数原样保留');if(route.value==='archives')await loadRoute();return r}
function show(title,fields,data,action,description=''){Object.assign(dialog,{open:true,title,fields,data:{...data},action,description})}
function field(key,label,type='text',required=true,options){return {key,label,type,required,options}}
async function saveDialog(){const wasControl=dialog.title==='确认设备控制';await dialog.action(dialog.data);dialog.open=false;await refresh();await loadRoute();if(!wasControl)notify('已保存')}
function newRecord(type='观察',photos=[]){show(type==='观察'?'新增观察记录':'标记关键节点',[field('title','记录标题'),field('type','记录类型','select',true,['观察','播种','定植','浇水','补光','施肥','采收','异常']),field('content','观察内容','textarea')],{title:'',content:'',type,photos},async d=>api('/records',{...d,device:deviceId.value,batch:current.value.batch,values:values.value,units:current.value.latest?.units||{}}))}
function viewSource(id){const item=sources.value.find(k=>k.id===id)||answer.value?.items.find(k=>k.id===id);if(!item)return;show(item.id+' · '+item.title,[],{},null,item.content+'\n\n来源：'+item.source)}
function configureDevice(d=null){show(d?'编辑设备配置':'添加水培设备',[field('id','设备编号'),field('name','设备名称'),field('group','班级 / 分组'),field('batch','当前茬次'),field('planted','定植日期','date'),field('source','数据来源','select',true,['mqtt'])],d?{...d}:{id:'HY-00'+(devices.value.length+1),name:'水培设备 0'+(devices.value.length+1),group:'未分组',batch:'',planted:new Date().toISOString().slice(0,10),source:'mqtt'},async data=>api('/devices'+(d?'/'+d.id:''),data,d?'PUT':'POST'),'添加实际设备信息后，等待 MQTT 真实遥测。')}
function control(key,state){const name=actuators.find(a=>a[0]===key)[1];show('确认设备控制',[],{},async()=>{const r=await api(`/devices/${deviceId.value}/commands`,{actuator:key,state,confirmed:true});notify(r.status==='simulated'?'模拟控制已执行，未发送到真实设备':'指令已发送，等待设备回执')},`${current.value.name} · ${state?'开启':'关闭'}${name}\n${current.value.source==='demo'?'当前为演示设备，本次仅模拟状态变化。':'指令有效期 30 秒。只有收到匹配的设备回执，才会更新执行器状态。'}`)}
function hardwareCommand({cmd,data,label}){show('确认设备控制',[],{},async()=>{await api(`/devices/${deviceId.value}/protocol-commands`,{cmd,data,confirmed:true});notify('指令已发送，等待设备回执与状态同步')},`${current.value.name} · ${label}\n本次操作会发送到真实设备。页面等待设备上报状态后更新。`)}
function modeChange(){if(current.value.hardware_mode){const next=current.value.mode==='manual'?'auto':'manual';show('切换设备工作模式',[],{},async()=>{await api(`/devices/${deviceId.value}/mode`,{mode:next,confirmed:true});notify('请求已发送，等待设备 state 同步')},'通过协议 CMD 08 切换 ESP32 工作模式。AI 智控在设备固件中运行。');return}const mode=current.value.mode==='manual'?'auto':'manual';if(mode==='manual'){run(async()=>{await api(`/devices/${deviceId.value}/mode`,{mode});await refresh();notify('已切换手动模式')});return}show('启用自动策略',[],{},async()=>{await api(`/devices/${deviceId.value}/mode`,{mode,confirmed:true});notify('阈值自动策略已启用')},'规则：液位低于 20% 关闭水泵；光照低于 8500 lx 开灯、高于 10000 lx 关灯；空气温度高于 29°C 开通风、低于 27°C 关通风；湿度低于 50% 开水雾、高于 60% 关水雾。\n每 10 秒评估一次。遥测过期、MQTT 断开或回执超时会暂停策略。'+(current.value.source==='demo'?'\n当前设备只模拟执行。':'\n确认后可能向真实设备发送控制指令。'))}

function fmt(t){return t?new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function commandName(record){return record.protocol==='tomato_v1_1'?({'01':'红灯亮度','02':'蓝灯亮度','03':'雾化泵','04':'补光灯总开关','05':'补光阶段','06':'泵运行间隔','07':'泵运行时长','08':'设备工作模式','09':'休息时段'}[record.cmd]||record.actuator):(actuators.find(a=>a[0]===record.actuator)?.[1]||record.actuator)}
function commandValue(record){if(record.protocol!=='tomato_v1_1')return record.state?'开启':'关闭';const data=record.data||{},value=data.value;if(record.cmd==='09')return `${String(data.start_hour).padStart(2,'0')}:${String(data.start_minute).padStart(2,'0')}–${String(data.end_hour).padStart(2,'0')}:${String(data.end_minute).padStart(2,'0')}`;if(['01','02'].includes(record.cmd))return value+'%';if(record.cmd==='05')return ['出苗','壮苗','营养生长','开花 / 坐果','果实膨大'][value-1]||'—';if(record.cmd==='06')return value+' 分钟';if(record.cmd==='07')return value+' 秒';if(record.cmd==='08')return value===1?'设备 AI 智控':'手动模式';return value?'开启':'关闭'}
function stateText(s){return {sent_unconfirmed:'已发送 · 待设备确认',acknowledged:'设备已确认',simulated:'模拟已执行',timeout:'回执超时',failed:'执行失败',claimed:'已领取',submitted:'已提交',evaluated:'已评价'}[s]||s}
function pickPhoto(purpose){photoPurpose.value=purpose;uploadEl.value.click()}
async function uploadFile(file,context={device:deviceId.value,batch:current.value.batch,captureSource:'upload'}){const fd=new FormData();fd.append('file',file);fd.append('device',context.device);fd.append('batch',context.batch||'');fd.append('capture_source',context.captureSource||'upload');return api('/photos',fd)}
async function savePendingPhoto(){
 const pending=pendingPhoto.value;if(!pending)return;
 if(!pending.photo)pending.photo=await uploadFile(pending.file,pending);
 const photo=pending.photo;
 if(pending.purpose==='recognize'){recognition.value=await api('/recognitions',{photo_id:photo.id,demo:false,confidence_threshold:pending.confidence});await loadRoute();notify('识别结果、原图和标注图已存入档案')}
 else if(pending.purpose==='task'){dialog.data.photos=[...(dialog.data.photos||[]),photo.id];notify('成果照片已附加')}
 else{newRecord('观察',[photo.id]);dialog.data.title='照片观察记录';notify('照片已上传，请补充观察内容')}
 pendingPhoto.value=null;cameraOpen.value=false;
}
async function receivePhoto({file,captureSource='upload'}){pendingPhoto.value={file,captureSource,purpose:photoPurpose.value,device:deviceId.value,batch:current.value.batch,confidence:confidencePercent.value/100,photo:null};await run(savePendingPhoto)}
async function uploaded(event){const file=event.target.files[0];event.target.value='';if(file)await receivePhoto({file})}
async function openCamera(purpose='archive',mode='local'){if(!deviceId.value)throw new Error('请先登记并选择实际设备和茬次。');await api('/devices');photoPurpose.value=purpose;cameraMode.value=mode;pendingPhoto.value=null;error.value='';message.value='';cameraOpen.value=true}
// 后端 YAML 保存远程摄像头默认地址；只在进入页面时读取，避免覆盖正在编辑的地址草稿。
async function loadCameraConfig(){try{const c=await api('/camera/config');savedCameraUrl.value=c.url;if(!cameraOpen.value)remoteCameraUrl.value=c.url}catch(e){error.value='摄像头默认地址读取失败：'+e.message}}
async function saveCameraAddress(url){const saved=await api('/camera/config',{url},'PUT');savedCameraUrl.value=saved.url;remoteCameraUrl.value=saved.url;notify('已保存为默认摄像头地址：'+saved.url)}
function closeCamera(){cameraOpen.value=false;pendingPhoto.value=null;error.value=''}
async function saveScreenshot(kind='graph'){const data=kind==='trend'?trendRef.value?.image():await toPng(workspace.value,{pixelRatio:1,backgroundColor:'#fcfbf8'});if(!deviceId.value)throw new Error('请先选择实际设备，再将截图保存到档案。');if(!data)return;const blob=await (await fetch(data)).blob();const p=await uploadFile(new File([blob],'screenshot.png',{type:'image/png'}));await api('/records',{title:kind==='trend'?'环境曲线截图':'知识问答截图',content:'页面留存',type:'截图',device:deviceId.value,batch:current.value.batch,photos:[p.id]});notify('截图已保存到生长档案')}
function newTask(){show('发布课程任务',[field('title','任务名称'),field('description','任务要求','textarea'),field('deadline','截止日期','date'),field('hours','课时数','number')],{title:'',description:'',deadline:'2026-10-01',hours:2},d=>api('/tasks',d))}
function submitTask(task){const sub=submissions.value.find(x=>x.task_id===task.id&&x.owner===user.value.role);show('提交成果 · '+task.title,[field('content','实训报告','textarea')],{content:sub?.content||'',photos:sub?.photos||[],records:sub?.records||[]},d=>api(`/tasks/${task.id}/submit`,d),'填写实训过程、观察现象与结论，可附加照片和当前环境快照。')}
function evaluate(sub){show('评价学生成果',[field('evaluation','评语','textarea'),field('score','评价分数','number')],{evaluation:sub.evaluation||'',score:sub.score||85,photos:sub.photos||[]},d=>api(`/submissions/${sub.id}/evaluate`,d),sub.content)}
function linkTask(record){show('将档案提交到课程任务',[field('task','课程任务','select',true,tasks.value.map(t=>({value:t.id,label:t.title})))],{task:tasks.value[0]?.id},d=>api(`/tasks/${d.task}/submit`,{content:record.content||record.title,photos:record.photos||[],records:[record.id]}))}
async function archiveToTask(record){tasks.value=await api('/tasks');if(!tasks.value.length)throw new Error('尚无课程任务，请先发布任务。');linkTask(record)}
async function saveTaskSnapshot(){const r=await snapshot();dialog.data.records=[...(dialog.data.records||[]),r.id];notify('环境数据已附加到成果')}
function compareToggle(r){if(compare.value.some(x=>x.id===r.id))compare.value=compare.value.filter(x=>x.id!==r.id);else compare.value.push(r)}
function recordDetail(r){show(r.title,[],{},null,r.content||JSON.stringify(r.values||{},null,2));dialog.data.photos=r.photos||[]}
function favoriteText(r){return r.answer?.generation?r.answer.generation.statements.map(s=>s.text+' ['+s.source_ids.join('、')+']').join('\n\n'):(r.content||[]).map(k=>k.content+' ['+k.id+']').join('\n\n')}
function shareText(text){if(navigator.share)navigator.share({title:'水培探究记录',text}).catch(()=>{});else navigator.clipboard.writeText(text).then(()=>notify('内容已复制，可粘贴分享')).catch(()=>notify('浏览器未开放复制权限'))}
function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){notify('当前浏览器不支持语音识别，请使用文字输入');return}const r=new SR();r.lang='zh-CN';r.onresult=e=>question.value=e.results[0][0].transcript;r.onerror=()=>notify('语音识别未完成，请检查麦克风权限');r.start()}
watch([deviceId,filter,batchFilter],()=>{recognition.value=null});watch(route,loadRoute);watch(deviceId,()=>{refresh().then(loadRoute)});watch(period,loadRoute);
onMounted(async()=>{window.addEventListener('hashchange',hash);try{
 const health=await api('/health');demo.value=health.demo;modelStatus.value=health.model||{ready:false,state:'not_configured'};
 try{user.value=await api('/session')}catch(e){if(e.status!==401)throw e;if(demo.value)user.value=await api('/session',{role:loginRole.value});else loginOpen.value=true}
 if(user.value){await refresh();await loadCameraConfig();await loadRoute();}
}catch(e){error.value=e.message}
 poll=setInterval(async()=>{if(!user.value)return;try{await refresh();if(['overview','iot'].includes(route.value))await loadRoute()}catch{}},2000)});
onBeforeUnmount(()=>{clearInterval(poll);clearTimeout(timer);closeCamera();setSessionRecovery(null);window.removeEventListener('hashchange',hash)});
</script>
<template>
<div class="app-shell">
 <header class="topbar"><div class="brand"><i class="ri-leaf-fill"/><strong>智慧劳动与科技教育平台</strong><span class="brand-divider"/><span class="brand-context">课堂教学 · 劳动实践 · 科技探究</span></div><div class="top-actions"><span class="campus-context"><i class="ri-building-4-fill"/> {{current.group||'番茄水培课堂'}}</span><span class="lab-context"><i class="ri-layout-grid-line"/><select aria-label="选择设备" v-model="deviceId"><option v-if="!devices.length" value="">未添加设备</option><option v-for="d in devices" :key="d.id" :value="d.id">{{d.name}}</option></select></span><span class="header-date"><i class="ri-calendar-line"/> {{dateLabel}}　{{weekdayLabel}}</span><button class="notification-button" aria-label="查看预警" @click="go('alerts')"><i class="ri-notification-3-fill"/><b v-if="alerts.length">{{alerts.length}}</b></button><div class="user-wrap"><button class="user-button" @click="profile=!profile"><i class="ri-account-circle-fill"/> {{user?.name||'登录'}} <i class="ri-arrow-down-s-line"/></button><div v-if="profile" class="user-menu"><p>本地角色账户 · {{user?.role}}</p><button @click="go('profile')">个人中心</button><button @click="go('alerts')">预警中心</button><button @click="loginOpen=true;profile=false">切换身份</button></div></div></div></header>
 <aside class="sidebar"><button v-for="n in nav" :key="n[0]" :class="{active:route===n[0]}" :aria-label="n[3]" @click="go(n[0])"><i :class="'ri-'+n[2]"/><span>{{n[1]}}</span></button><div class="sidebar-art"><img :src="campusSidebar" alt="用劳动创造美好，用科技点亮未来"/></div></aside>
 <nav class="mobile-nav" aria-label="移动端导航"><button v-for="n in [['overview','监控','home-5-fill'],['maturity','拍照','camera-fill'],['archives','记录','folder-open-fill'],['knowledge','问答','book-open-fill'],['growth','科普','seedling-line'],['profile','我的','account-circle-fill']]" :class="{active:route===n[0]}" @click="go(n[0])"><i :class="'ri-'+n[2]"/><span>{{n[1]}}</span></button></nav>
 <main class="main" ref="workspace">
 <div v-if="error" class="error-banner" role="alert"><i class="ri-error-warning-line"/> {{error}}<button aria-label="关闭错误提示" @click="error=''">关闭</button></div>
 <KnowledgeWorkspace v-if="route==='knowledge'&&user" :key="user.role" :device-id="deviceId" :can-teach="canTeach" :can-edit="canEdit" @error="error=$event" @notify="notify" @screenshot="run(()=>saveScreenshot('graph'))"/>
 <div v-else-if="route==='knowledge'" class="empty">请登录后查询知识资料。</div>
 <template v-else-if="route==='iot'&&!current.id"><div class="page-heading"><div><h1>智能温室物联网</h1><p>先配置 MQTT 连接，再添加实际设备并等待真实遥测。</p></div><button class="primary" @click="mqttDrawerOpen=true"><i class="ri-settings-3-line"/> MQTT 配置</button></div><MqttStatusPanel :mqtt="mqtt" :metrics="metrics"/><div class="empty"><h2>尚未添加真实设备</h2><p>添加实际设备并接入 MQTT 后显示实测数据。</p><button @click="go('devices')">设备管理</button></div></template>
 <TomatoGrowth v-else-if="route==='growth'"/>
 <template v-else-if="['overview','iot'].includes(route)">
  <div class="page-heading" :class="{'classroom-hero':route==='overview'}" :style="route==='overview'?{backgroundImage:`linear-gradient(90deg,#fff 0%,#fffffff0 28%,#ffffff14 62%),url(${classroomHero})`}:{}"><div class="hero-copy"><span class="eyebrow">{{current.id?current.group+' / '+current.batch+' · 第 '+growthDays+' 天':'番茄水培课程 · 等待绑定真实设备'}}</span><div class="hero-title-row"><i v-if="route==='overview'" class="ri-seedling-fill"/><h1>{{route==='overview'?'番茄水培课堂总览':'智能温室物联网'}}</h1><span v-if="route==='overview'" :class="['lesson-state',{online:current.online}]"><b/>{{current.online?'上课中':'等待设备'}}</span></div><p>{{!current.id?'尚未绑定真实设备 · 可先布置课堂任务':(current.source==='demo'?'演示数据 · 每 2 秒模拟采集':'MQTT 实时遥测')+' · '+(current.online?'数据在线':'等待数据')+' · '+(current.hardware_mode?(current.device_state?(current.device_state.control_mode===0?'手动模式':'设备 AI 智控'):'等待设备状态'):(current.mode==='manual'?'手动模式':'阈值自动模式'))}}</p></div><div class="actions"><button v-if="route==='iot'" @click="mqttDrawerOpen=true"><i class="ri-settings-3-line"/> MQTT 配置</button><template v-if="route==='overview'"><button class="primary" @click="go('iot')"><i class="ri-play-fill"/> 开始上课</button><button @click="canTeach?newTask():go('courses')"><i class="ri-settings-3-line"/> 布置任务</button></template><button class="primary" :disabled="busy||!canEdit||!current.id" @click="run(snapshot)"><i class="ri-save-line"/> {{route==='overview'?'保存课堂数据':'保存当前数据'}}</button></div></div>
  <div v-if="route==='overview'" class="overview-stats">
   <article class="stat-card green"><i class="ri-book-open-fill"/><div><span>课堂任务进度</span><strong>{{completedTasks}}<small>/ {{tasks.length}}</small></strong><div class="stat-progress"><b :style="{width:(tasks.length?completedTasks/tasks.length*100:0)+'%'}"/></div></div></article>
   <article class="stat-card blue"><i class="ri-router-line"/><div><span>设备在线</span><strong>{{onlineDevices}}<small>/ {{devices.length}}</small></strong><div class="stat-progress"><b :style="{width:(devices.length?onlineDevices/devices.length*100:0)+'%'}"/></div></div></article>
   <article class="stat-card indigo"><i class="ri-drop-fill"/><div><span>今日浇水次数</span><strong>{{summary.water_count??0}}<small>次</small></strong><p>来自真实执行记录</p></div></article>
   <article class="stat-card violet"><i class="ri-cpu-fill"/><div><span>AI 识别次数</span><strong>{{summary.recognition_count??0}}<small>次</small></strong><p>保留原图与标注</p></div></article>
   <article class="stat-card mint"><i class="ri-leaf-fill"/><div><span>番茄生长天数</span><strong>{{growthDays}}<small>天</small></strong><p>从定植日期开始</p></div></article>
  </div>
  <section v-if="route==='overview'&&!current.id" class="panel no-device-classroom"><i class="ri-router-line"/><div><h2>接入真实设备后开始课堂观测</h2><p>当前没有登记的水培设备，因此环境数据、控制状态与识别记录保持为空，不使用示例数据替代。</p></div><div class="actions"><button @click="mqttDrawerOpen=true">配置 MQTT</button><button class="primary" @click="go('devices')">添加设备</button></div></section>
  <MqttStatusPanel v-if="current.id&&(route==='iot'||current.hardware_mode)" :mqtt="mqtt" :device="current" :metrics="metrics"/><div v-if="current.id" class="metric-strip"><div v-for="m in metrics" :key="m[0]"><i :class="'ri-'+m[3]"/><span>{{m[1]}}</span><strong :class="{amber:m[0]==='ph'&&typeof values.ph==='number'&&values.ph<5.8}">{{values[m[0]]??'—'}}<small>{{metricUnit(m,current.latest||{units:current.metric_units})}}</small></strong></div></div>
  <div class="alert-strip" v-if="alerts.some(a=>a.device===deviceId)"><i class="ri-error-warning-line"/><span>{{alerts.filter(a=>a.device===deviceId).map(a=>a.title).join('、')}} · 请结合实测排查</span><button @click="go('alerts')">查看预警 <i class="ri-arrow-right-line"/></button></div>
  <div v-if="current.id" class="monitor-grid"><section class="panel"><div class="panel-heading"><h2>环境数据趋势</h2><div class="actions"><select aria-label="选择环境参数" v-model="metric"><option v-for="m in metrics" :value="m[0]">{{m[1]}}</option></select><div class="segmented"><button v-for="p in [['hour','小时'],['day','天'],['week','周']]" :class="{selected:period===p[0]}" @click="period=p[0]">{{p[1]}}</button></div></div></div><Trend ref="trendRef" :points="trend" :metric="metric"/><div class="panel-bottom"><span>{{period==='hour'?'分钟':'小时'}}聚合 · {{trend.length}} 个时间点</span><button :disabled="!canEdit||busy" @click="run(()=>saveScreenshot('trend'))">保存曲线截图</button></div></section><HardwareControls v-if="current.hardware_mode" :device="current" :connected="mqtt.connected&&mqtt.subscribed" :can-edit="canEdit" :can-teach="canTeach" :busy="busy" @command="hardwareCommand"/><section v-else class="panel control-panel"><div class="panel-heading"><h2>设备控制</h2><button v-if="canTeach" @click="modeChange">{{current.mode==='manual'?'切换自动':'切换手动'}}</button></div><div class="actuator" v-for="a in actuators.filter(a=>!current.supported_actuators||current.supported_actuators.includes(a[0]))"><i :class="'ri-'+a[2]"/><div><h3>{{a[1]}}</h3><p>{{a[3]}}</p></div><button role="switch" :aria-label="a[1]" :aria-checked="!!current.actuators?.[a[0]]" :class="['toggle',{on:current.actuators?.[a[0]]}]" :disabled="!canEdit" @click="control(a[0],!current.actuators?.[a[0]])"><span/></button></div><p class="muted">{{current.source==='demo'?'当前控制为模拟执行，不连接实体设备。':'设备状态仅在收到有效回执后更新。'}}</p></section></div>
  <div v-if="current.id" class="toolbar"><button :disabled="!canEdit" @click="newRecord('浇水')">标记关键节点</button><button @click="download('telemetry','csv',deviceId)">导出 CSV</button><button @click="download('telemetry','xlsx',deviceId)">导出 Excel</button><button @click="go('archives')">进入生长档案</button></div>
  <section class="panel" v-if="current.id&&route==='iot'"><div class="panel-heading"><h2>控制指令与回执</h2><span class="muted">发送状态与设备执行状态分开记录</span></div><table><thead><tr><th>时间</th><th>设备</th><th>执行器</th><th>操作</th><th>状态</th></tr></thead><tbody><tr v-for="c in commands.filter(c=>c.device===deviceId).slice(0,8)"><td>{{fmt(c.created_at)}}</td><td>{{c.device}}</td><td>{{commandName(c)}}</td><td>{{commandValue(c)}}</td><td><span class="tag">{{stateText(c.status)}}</span></td></tr></tbody></table><div v-if="!commands.some(c=>c.device===deviceId)" class="empty small">暂无控制指令</div></section>
  <section v-else-if="current.id&&route==='overview'" class="panel"><div class="panel-heading"><h2>最新 AI 识别</h2><button @click="go('maturity')">进入成熟度管理</button></div><div class="recognition-summary" v-if="rows[0]"><img :src="rows[0].annotated"/><div><h3>{{rows[0].mode==='demo'?'演示识别':'YOLO 识别'}} · {{fmt(rows[0].created_at)}}</h3><p>{{rows[0].detections.length}} 个识别目标 · 原图与标注图已留存</p></div></div><div v-else class="empty small">还没有识别记录，上传植株照片开始记录。</div></section>
 </template>
 <template v-else-if="route==='archives'">
  <div class="page-heading"><div><span class="eyebrow">{{current.name}} / {{current.batch}}</span><h1>生长档案</h1><p>把每一次观察、浇水和识别，留在同一条生长时间线上。</p></div><div class="actions"><button @click="pickPhoto('archive')" :disabled="!canEdit"><i class="ri-image-add-line"/> 上传照片</button><button class="primary" @click="newRecord()" :disabled="!canEdit"><i class="ri-add-line"/> 新增记录</button></div></div>
  <div class="toolbar"><input v-model="filter" placeholder="搜索观察内容或事件"/><input v-model="batchFilter" placeholder="按茬次筛选"/><button @click="run(snapshot)" :disabled="!canEdit||busy">保存当前数据</button><button @click="download('records','pdf',deviceId)">生成档案报告</button><button @click="download('records','csv',deviceId)">CSV</button><button @click="download('records','zip',deviceId)">照片与档案包</button><button @click="go('devices')">设备对比</button></div>
  <section v-if="archiveCompare.length" class="panel archive-comparison"><div class="panel-heading"><h2>生长记录对比 · {{archiveCompare.length}} 组</h2><button @click="archiveCompare=[]">清空</button></div><div class="table-scroll"><table><thead><tr><th>设备 / 茬次 / 时间</th><th v-for="m in metrics">{{m[1]}}</th></tr></thead><tbody><tr v-for="r in archiveCompare"><td>{{r.device}} / {{r.batch}}<small>{{fmt(r.created_at)}}</small></td><td v-for="m in metrics">{{r.values?.[m[0]]??'—'}} {{metricUnit(m,r)}}</td></tr></tbody></table></div></section>
  <div class="timeline"><article v-for="r in allFiltered" :key="r.id"><div class="timeline-date">{{fmt(r.created_at)}}<span>{{r.type}}</span></div><section><div class="row-between"><h3>{{r.title}}</h3><span class="tag">{{r.batch}}</span></div><p>{{r.content}}</p><div class="mini-values" v-if="r.values"><span v-for="m in metrics" v-show="r.values[m[0]]!==undefined">{{m[1]}} <b>{{r.values[m[0]]??'暂无读数'}}{{r.values[m[0]]==null?'':metricUnit(m,r)}}</b></span></div><div class="photo-row" v-if="r.photos?.length"><a v-for="id in r.photos" :href="'/api/photos/'+id" target="_blank"><img :src="'/api/photos/'+id" alt="生长档案照片"/></a></div><div class="record-actions"><button @click="recordDetail(r)">查看记录</button><button @click="archiveCompare.some(x=>x.id===r.id)?archiveCompare=archiveCompare.filter(x=>x.id!==r.id):archiveCompare.push(r)">{{archiveCompare.some(x=>x.id===r.id)?'移出对比':'加入对比'}}</button><button v-if="canEdit" @click="run(()=>archiveToTask(r))">保存到课程任务</button><button @click="shareText(r.title+'\n'+r.content)">分享</button></div></section></article><div v-if="!allFiltered.length" class="empty">当前筛选下暂无生长记录。</div></div>
 </template>
 <template v-else-if="route==='maturity'">
  <div class="page-heading"><div><h1>成熟度管理中心</h1><p>识别果实成熟度，保留原图、标注与采摘依据。</p></div><div class="actions"><button @click="run(()=>openCamera('recognize'))" :disabled="busy||!canEdit||!deviceId||!modelStatus.ready">拍照识别</button><button @click="run(()=>openCamera('recognize','remote'))" :disabled="busy||!canEdit||!deviceId||!modelStatus.ready"><i class="ri-router-line"/> 远程摄像头</button><button class="primary" @click="pickPhoto('recognize')" :disabled="busy||!canEdit||!deviceId||!modelStatus.ready"><i class="ri-upload-2-line"/> 上传照片并识别</button></div></div><div class="notice"><i class="ri-information-line"/> <span>{{modelNotice}}{{!deviceId?' · 请先在设备管理中登记实际设备与茬次，再上传照片。':''}}</span></div>
  <div class="confidence-control">
   <div class="confidence-setting"><label for="confidence-threshold">最低置信度 <strong>{{confidencePercent}}%</strong></label><input id="confidence-threshold" v-model.number="confidencePercent" type="range" min="10" max="95" step="5" :disabled="busy" :aria-valuetext="confidencePercent+'%'" aria-describedby="confidence-help"/><button type="button" @click="confidencePercent=65" :disabled="busy||confidencePercent===65">恢复默认 65%</button></div>
   <p id="confidence-help">低于阈值的目标不显示，也不计入统计。新识别使用此阈值；历史记录仅筛选显示，导出保留原始存档。</p>
  </div>
  <div class="toolbar"><input v-model="filter" placeholder="检索时间、成熟度或编号"/><input v-model="batchFilter" placeholder="按茬次筛选"/><button @click="download('recognitions','pdf',deviceId)">生成采摘报告</button><button @click="download('recognitions','json',deviceId)">保存识别结果</button><button @click="download('recognitions','zip',deviceId)">导出识别照片</button></div>
  <section v-if="recognition||allFiltered[0]" class="panel recognition-detail"><div class="panel-heading"><h2>{{(recognition||allFiltered[0]).mode==='demo'?'演示识别结果':'识别结果'}}</h2><span>{{fmt((recognition||allFiltered[0]).created_at)}}</span></div><div class="summary-strip" aria-label="识别统计"><div><span>果实数量</span><strong>{{recognitionStats.fruit_count}}<small>个</small></strong></div><div v-for="(count,label) in recognitionStats.maturity_distribution" :key="label"><span>{{label}}</span><strong>{{count}}<small>个</small></strong></div><div><span>平均置信度</span><strong>{{recognitionStats.average_confidence===null?'—':(recognitionStats.average_confidence*100).toFixed(1)+'%'}}</strong></div></div><p v-if="!recognitionStats.fruit_count" class="notice">当前阈值下没有符合条件的果实，可适当降低最低置信度。</p><p class="confidence-summary" aria-live="polite">显示 {{recognitionStats.fruit_count}} / {{selectedRecognition.detections.length}} 个目标 · 已过滤 {{selectedRecognition.detections.length-recognitionStats.fruit_count}} 个低置信度目标</p><p v-if="confidencePercent/100 < (selectedRecognition.model?.confidence_threshold||0)" class="confidence-summary">该记录仅保存置信度 ≥{{Math.round(selectedRecognition.model.confidence_threshold*100)}}% 的目标；查看更低置信度结果需重新上传原图识别。</p><div class="image-compare"><figure><img :src="(recognition||allFiltered[0]).original" alt="识别原图"/><figcaption>原图</figcaption></figure><figure><RecognitionImage :key="selectedRecognition.id" :source="selectedRecognition.original" :detections="visibleDetections(selectedRecognition)"/><figcaption>筛选标注图 · ≥{{confidencePercent}}% · 编号对应下方结果</figcaption></figure></div><table><thead><tr><th>果实编号</th><th>成熟度</th><th>置信度</th><th>采摘建议</th></tr></thead><tbody><tr v-for="(d,i) in visibleDetections(selectedRecognition)"><td>{{i+1}}</td><td><span class="tag">{{d.label}}</span></td><td>{{(d.confidence*100).toFixed(1)}}%</td><td>{{d.label==='成熟'?'人工复核后采摘':'继续观察'}}</td></tr></tbody></table></section><div class="empty" v-else><i class="ri-camera-lens-line"/><h3>记录第一张果实照片</h3><p>上传照片后，原图和标注图会自动关联当前设备与茬次。</p></div>
  <div class="document-list"><article v-for="r in allFiltered"><div><h3>{{r.batch}} · {{fmt(r.created_at)}}</h3><p>显示 {{visibleDetections(r).length}} / {{r.detections.length}} 个果实 · {{r.mode==='demo'?'演示数据':'模型推理'}}</p></div><div class="actions"><button @click="recognition=r">查看</button><button @click="compareToggle(r)">{{compare.some(x=>x.id===r.id)?'移出对比':'加入对比'}}</button></div></article></div><section v-if="compare.length" class="panel"><div class="panel-heading"><h2>识别对比 · {{compare.length}} 组</h2><button @click="compare=[]">清空对比</button></div><table><thead><tr><th>设备 / 茬次</th><th>时间</th><th>成熟</th><th>半成熟</th><th>未成熟</th><th>平均置信度</th></tr></thead><tbody><tr v-for="r in compare"><td>{{r.device}} / {{r.batch}}</td><td>{{fmt(r.created_at)}}</td><td v-for="label in ['成熟','半成熟','未成熟']">{{visibleDetections(r).filter(d=>d.label===label).length}}</td><td>{{filteredStats(r).average_confidence===null?'—':(filteredStats(r).average_confidence*100).toFixed(1)+'%'}}</td></tr></tbody></table></section>
 </template>
 <template v-else-if="route==='logs'">
  <div class="page-heading"><div><h1>AI 日志</h1><p>追溯判断、工具调用、数据来源与设备执行结果。</p></div><div class="actions"><button @click="download('logs','csv')">导出日志</button><button class="primary" @click="download('logs','pdf')">生成复盘报告</button></div></div><input class="filter-input" v-model="filter" placeholder="搜索判断、设备或来源编号"/><div class="log-list"><article v-for="r in allFiltered"><i :class="r.level==='error'?'ri-error-warning-line':'ri-history-line'"/><div><div class="row-between"><h3>{{r.title}} <span class="tag" v-if="r.flagged">已标记问题</span></h3><time>{{fmt(r.created_at)}}</time></div><p>{{r.detail}}</p><span class="muted">{{r.device?'设备 '+r.device:'系统事件'}}</span><button class="source-chip" v-for="id in r.sources" @click="run(async()=>{sources=await api('/knowledge');viewSource(id)})">{{id}}</button><details v-if="r.evidence" class="log-evidence"><summary>查看当时的关联证据</summary><p v-if="r.evidence.environment">环境采集于 {{fmt(r.evidence.environment.ts)}} · {{r.evidence.environment.source==='demo'?'演示数据':'MQTT 遥测'}} · 茬次 {{r.evidence.batch}}</p><p v-if="r.evidence.environment"><span v-for="m in metrics" :key="m[0]">{{m[1]}} {{r.evidence.environment.values[m[0]]??'—'}} {{metricUnit(m,r.evidence.environment)}}　</span></p><p v-else>本事件未关联环境采样。</p><div v-for="k in r.evidence.knowledge" :key="k.id"><strong>{{k.id}} · {{k.title}}</strong><p>{{k.content}}</p><small>记录时的来源：{{k.source}}</small></div><div v-if="r.evidence.recognition"><p>识别 {{r.evidence.recognition.id}} · {{r.evidence.recognition.mode==='demo'?'演示识别':'YOLO 推理'}}</p><img :src="r.evidence.recognition.annotated" alt="该次识别的标注图" style="max-width:320px;width:100%"/></div><p v-if="r.evidence.command">指令 {{r.evidence.command.id}} · {{commandName(r.evidence.command)}} → {{commandValue(r.evidence.command)}} · {{stateText(r.evidence.command.status)}}</p></details></div><button v-if="canTeach" @click="run(async()=>{await api('/logs/'+r.id,{flagged:!r.flagged},'PATCH');await loadRoute()})">{{r.flagged?'取消标记':'标记问题'}}</button></article><div v-if="!allFiltered.length" class="empty">没有匹配的日志。</div></div>
 </template>
 <template v-else-if="route==='courses'">
  <div class="page-heading"><div><span class="eyebrow">校本课程 · 多源感知水培种植</span><h1>课程与实训中心</h1><p>从传感器校准到生长探究，让每一次劳动成为学习成果。</p></div><button v-if="canTeach" class="primary" @click="newTask"><i class="ri-add-line"/> 发布任务</button></div><div class="course-summary"><div><strong>{{tasks.length}}</strong> 个实训项目</div><div><strong>{{tasks.reduce((a,t)=>a+t.hours,0)}}</strong> 课时</div><div><strong>{{submissions.filter(s=>s.status==='submitted'||s.status==='evaluated').length}}</strong> 份已提交成果</div></div><div class="course-list"><article v-for="(t,i) in tasks.slice().reverse()"><span class="course-no">{{String(i+1).padStart(2,'0')}}</span><div class="course-info"><h3>{{t.title}}</h3><p>{{t.description}}</p><small>{{t.hours}} 课时 · 截止 {{t.deadline}}</small><div v-for="s in submissions.filter(s=>s.task_id===t.id)" class="submission"><span class="tag">{{stateText(s.status)}}</span><span>{{({student:'学生',teacher:'教师',admin:'管理员',parent:'家长'})[s.owner]||s.owner}} {{s.evaluation?`· ${s.score} 分 · ${s.evaluation}`:''}}</span><button v-if="canTeach&&['submitted','evaluated'].includes(s.status)" @click="evaluate(s)">查看与评价</button></div></div><div class="actions" v-if="canEdit"><button @click="run(async()=>{await api('/tasks/'+t.id+'/claim',{});await loadRoute();notify('任务已领取')})">领取任务</button><button class="primary" @click="submitTask(t)">提交成果</button></div></article></div>
 </template>
 <template v-else-if="route==='devices'">
  <div class="page-heading"><div><h1>多设备管理</h1><p>按班级和茬次组织设备，统一查看环境与生长状态。</p></div><div class="actions"><button v-if="canTeach" class="primary" @click="configureDevice()">添加设备</button></div></div><div class="toolbar"><button @click="download('devices','xlsx')">导出多设备数据</button><button @click="download('devices','pdf')">生成对比报告</button><span class="muted">当前身份：{{user?.name}} · {{canTeach?'可管理设备':'只读设备配置'}}</span></div><div class="table-scroll"><table class="device-table"><thead><tr><th>设备 / 班级</th><th>茬次</th><th>数据来源</th><th>状态</th><th v-for="m in metrics">{{m[1]}}</th><th>操作</th></tr></thead><tbody><tr v-for="d in devices"><td><strong>{{d.name}}</strong><small>{{d.id}} · {{d.group}}</small></td><td>{{d.batch}}</td><td>{{d.source==='demo'?'演示':'MQTT'}}</td><td><span :class="['status-dot',{online:d.online}]"/>{{d.online?'在线':'离线'}}</td><td v-for="m in metrics">{{d.latest?.values[m[0]]??'—'}}<small>{{metricUnit(m,d.latest||{units:d.metric_units})}}</small></td><td><button v-if="canTeach" @click="configureDevice(d)">配置</button><button @click="deviceId=d.id;go('iot')">查看</button></td></tr></tbody></table></div>
 </template>
 <template v-else-if="route==='alerts'">
  <div class="page-heading"><div><h1>预警中心</h1><p>核对异常、留存处理过程，并持续观察参数是否恢复。</p></div><button @click="go('iot')">进入远程控制</button></div><div class="document-list"><article v-for="a in alerts"><i class="ri-alarm-warning-line alert-icon"/><div><h3>{{a.title}} <span class="tag">{{a.resolved?'已人工标记处理':'待处理'}}</span></h3><p>{{a.device}} · {{a.source==='demo'?'演示预警':'设备预警'}} · {{a.advice}}</p><small v-if="a.resolved">当前读数仍超阈值，请继续观察。</small></div><div class="actions"><button @click="deviceId=a.device;newRecord('异常')">保存预警记录</button><button @click="deviceId=a.device;run(()=>openCamera())">拍照记录</button><button :disabled="a.resolved||!canEdit" @click="run(async()=>{await api('/alerts/'+a.id+'/resolve',{});await refresh();notify('已标记处理，仍保留异常读数')})">标记已解决</button></div></article><div class="empty" v-if="!alerts.length">当前没有环境预警。</div></div>
 </template>
 <template v-else-if="route==='profile'">
  <div class="page-heading"><div><h1>{{user?.name}}的个人中心</h1><p>我的档案、收藏、任务与备份。</p></div></div><div class="toolbar"><button @click="go('archives')">我的档案</button><button @click="go('courses')">我的任务</button><button @click="go('devices')">我的设备</button><button @click="download('records','json')">数据备份</button><button @click="download('records','zip')">照片备份</button><button @click="download('records','pdf')">导出个人档案</button></div><section class="achievements"><div><span>劳动成长积分</span><strong>{{achievements.points}}</strong><small>按任务提交与评价记录计算</small></div><div v-for="b in achievements.badges" :class="{unearned:!b.earned}"><i :class="'ri-'+b.icon"/><strong>{{b.name}}</strong><small>{{b.earned?'已获得':'继续参与实训即可解锁'}}</small></div></section><h2>我的收藏</h2><div class="document-list"><article v-for="r in rows"><div><h3>{{r.title}}</h3><p style="white-space:pre-wrap">{{favoriteText(r)}}</p><small v-if="r.answer?.generation">本地模型：{{r.answer.generation.model}} · 保存时的回答快照</small><details v-if="r.answer"><summary>查看保存时的来源原文</summary><div v-for="k in r.answer.items" :key="k.id"><strong>{{k.id}} · {{k.verified?'已核验':'待核验'}}</strong><p>{{k.content}}</p><small>{{k.source}}</small></div></details></div><button @click="shareText(favoriteText(r))">分享</button></article><div class="empty" v-if="!rows.length">还没有收藏答案。</div></div>
 </template>
 <div v-if="loading" class="loading-line">正在加载…</div>
 </main>
 <footer class="context-bar"><div><i class="ri-bar-chart-fill"/><strong>当前环境</strong><span>pH {{values.ph??'—'}}</span><span>·</span><span>EC {{values.ec??'—'}} mS/cm</span><span>·</span><span>水温 {{values.water_temp??'—'}}°C</span><span>·</span><span>{{current.source==='demo'?'演示数据':current.online?'实时数据':'等待遥测'}}</span></div><div><button class="text-button link-blue" @click="go('iot')">前往物联网检查 <i class="ri-arrow-right-line"/></button><span class="footer-divider"/><span><b :class="['status-dot',{online:mqtt.connected}]"/> MQTT · {{mqtt.connected?'已连接':'未连接'}}</span></div></footer>
 <div v-if="message" class="toast" role="status"><i class="ri-checkbox-circle-line"/>{{message}}</div>
 <MqttConfigDrawer v-if="mqttDrawerOpen" :mqtt="mqtt" @close="mqttDrawerOpen=false" @changed="refresh"/>

 <div v-if="dialog.open" class="overlay modal-overlay" @click.self="dialog.open=false"><section class="modal" role="dialog" :aria-label="dialog.title"><div class="drawer-heading"><h2>{{dialog.title}}</h2><button aria-label="关闭对话框" @click="dialog.open=false"><i class="ri-close-line"/></button></div><p v-if="dialog.description" class="dialog-description">{{dialog.description}}</p><form @submit.prevent="run(saveDialog)"><label v-for="f in dialog.fields">{{f.label}}<textarea v-if="f.type==='textarea'" v-model="dialog.data[f.key]" :required="f.required" rows="5"/><select v-else-if="f.type==='select'" v-model="dialog.data[f.key]"><option v-for="o in f.options" :value="typeof o==='string'?o:o.value">{{typeof o==='string'?o:o.label}}</option></select><input v-else :type="f.type" v-model="dialog.data[f.key]" :required="f.required" :min="f.key==='score'?0:undefined" :max="f.key==='score'?100:undefined"/></label><div v-if="dialog.title.startsWith('提交成果')" class="toolbar"><button type="button" @click="pickPhoto('task')">上传成果照片</button><button type="button" @click="run(saveTaskSnapshot)">保存实训数据</button><small>{{dialog.data.photos?.length||0}} 张照片 · {{dialog.data.records?.length||0}} 份数据</small></div><div class="photo-row" v-if="dialog.data.photos?.length"><img v-for="id in dialog.data.photos" :src="'/api/photos/'+id" alt="记录照片"/></div><div class="error-inline" v-if="error">{{error}}</div><div class="modal-footer"><button type="button" @click="dialog.open=false">{{dialog.action?'取消':'关闭'}}</button><button v-if="dialog.action" class="primary" :disabled="busy">{{busy?'处理中…':dialog.title==='确认设备控制'?'确认发送':'保存'}}</button></div></form></section></div>
 <div v-if="loginOpen" class="overlay modal-overlay" style="z-index:100"><section class="modal login"><h2>{{demo?'选择本地角色':'账户登录'}}</h2><p>{{demo?'不同身份对应不同的课程与设备权限。':'请输入对应角色的本机账户密码。'}}</p><form @submit.prevent="run(()=>signIn(loginRole,loginPassword))"><label>身份<select v-model="loginRole"><option value="teacher">教师</option><option value="student">学生</option><option value="admin">管理员</option><option value="parent">家长 · 成果只读</option></select></label><label v-if="!demo">密码<input type="password" v-model="loginPassword" required/></label><div class="error-inline" v-if="error">{{error}}</div><button class="primary wide" :disabled="busy">进入系统</button></form></section></div>
 <CameraDialog v-if="cameraOpen" v-model:remote-url="remoteCameraUrl" :initial-mode="cameraMode" :busy="busy" :submit-error="error" :recognize="photoPurpose==='recognize'" :saved-url="savedCameraUrl" @capture="receivePhoto" @retry="run(savePendingPhoto)" @save-address="run(()=>saveCameraAddress($event))" @discard="pendingPhoto=null;error=''" @close="closeCamera"/>
 <div v-if="pendingPhoto&&!cameraOpen&&!loginOpen" class="toast" role="status">照片已暂存。<button :disabled="busy" @click="run(savePendingPhoto)">重试保存</button><button :disabled="busy" @click="pendingPhoto=null">放弃</button></div>
 <input ref="uploadEl" class="hidden" type="file" accept="image/*" @change="uploaded"/><input ref="cameraEl" class="hidden" type="file" accept="image/*" capture="environment" @change="uploaded"/>
</div>
</template>
